# Define keywords.
ALL = "all"
AND = "and"
ANY = "any"
ASCII = "ascii"
AT = "at"
BASE64 = "base64"
BASE64_WIDE = "base64wide"
CONDITION = "condition"
CONTAINS = "contains"
ENTRY_POINT = "entrypoint"
FALSE = "false"
FILE_SIZE = "filesize"
FOR = "for"
FULL_WORD = "fullword"
GLOBAL ="global"
IMPORT = "import"
IN = "IN"
INCLUDE = "include"
INT_16 = "int16"
INT_16_BE = "int16be"
INT_32 = "int32"
INT_32_BE = "int32be"
INT_8 = "int8"
INT_8_BE = "int8be"
MATCHES = "matches"
META = "meta"
NO_CASE = "nocase"
NOT = "not"
OF = "of"
OR = "or"
PRIVATE = "private"
RULE = "rule"
STRINGS = "strings"
THEM = "them"
TRUE = "true"
U_INT_16 = "uint16"
U_INT_16_BE = "uint16be"
U_INT_32 = "uint32"
U_INT_32_BE = "uint32be"
U_INT_8 = "uint8"
U_INT_8_BE = "uint8be"
WIDE = "wide"
XOR = "xor"


KEYWORDS = [ALL, AND, ANY, ASCII, AT, BASE64, BASE64_WIDE, CONDITION, CONTAINS, ENTRY_POINT, FALSE, FILE_SIZE, FOR,
            FULL_WORD, GLOBAL, IMPORT, IN, INCLUDE, INT_16, INT_16_BE, INT_32, INT_8, INT_8_BE, MATCHES, META, NO_CASE,
            NOT, OF, OR, PRIVATE, RULE, STRINGS, THEM, TRUE, U_INT_16, U_INT_16_BE, U_INT_32, U_INT_32_BE, U_INT_8,
            U_INT_8_BE, WIDE, XOR]